---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ecoSynthesis

<!-- badges: start -->
<!-- badges: end -->

The goal of ecoSynthesis is to ...

## Installation

You can install the development version of ecoSynthesis from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("Ecosystem-Indicators-Workflows/ecoSynthesis")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ecoSynthesis)

input_table <- data.frame(
    re1 = c("Semi-deciduous Forest","Deciduous Forest","Wet Montane Forest","Dry Montane Forest"),
    efg1 = c("T1.1", "T1.2", "T1.1", "T1.2"),
    memb1 = c(80,80,70,50),
    efg2 = c("T1.2", "T1.1", "T1.3", "T1.3"),
    memb2 = c(20,20,30,50)
)

membership_table(
    input_table, 
    "re1",
    c("efg1","efg2","efg3"),
    c("memb1","memb2"),
    target="T1.3")
```



